name: go-ci
description: Common Go CI steps (fmt, vet, build, coverage, artifacts, codecov)
inputs:
  os-tag:
    description: OS label for flags/artifact naming (ubuntu|macos|windows)
    required: true
  go-tag:
    description: Go version label for flags/artifact naming
    required: true
  codecov:
    description: Upload to Codecov (true/false)
    required: false
    default: "false"

runs:
  using: composite
  steps:
    # -------- ensure cover tool in PATH (bash) --------
    - name: Ensure cover tool (bash)
      if: inputs.os-tag != 'windows'
      shell: bash
      run: |
        go install golang.org/x/tools/cmd/cover@latest
        echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

    # -------- ensure cover tool in PATH (pwsh) --------
    - name: Ensure cover tool (pwsh)
      if: inputs.os-tag == 'windows'
      shell: pwsh
      run: |
        go install golang.org/x/tools/cmd/cover@latest
        echo "$env:GOPATH\bin" >> $env:GITHUB_PATH

    # -------- deps --------
    - name: Download deps
      shell: bash
      if: inputs.os-tag != 'windows'
      run: go mod download

    - name: Download deps (windows)
      shell: pwsh
      if: inputs.os-tag == 'windows'
      run: go mod download

    # -------- fmt-check --------
    - name: fmt-check
      if: inputs.os-tag != 'windows'
      shell: bash
      run: |
        set -e
        OUT=$(gofmt -l .)
        if [ -n "$OUT" ]; then
          echo "Files not formatted:"
          echo "$OUT"
          exit 1
        fi

    - name: fmt-check (windows)
      if: inputs.os-tag == 'windows'
      shell: pwsh
      run: |
        $out = gofmt -l .
        if ($out) {
          echo "Files not formatted:"
          echo $out
          exit 1
        }

    # -------- vet --------
    - name: vet
      if: inputs.os-tag != 'windows'
      shell: bash
      run: go vet ./...

    - name: vet (windows)
      if: inputs.os-tag == 'windows'
      shell: pwsh
      run: go vet ./...

    # -------- build --------
    - name: build
      if: inputs.os-tag != 'windows'
      shell: bash
      run: go build ./...

    - name: build (windows)
      if: inputs.os-tag == 'windows'
      shell: pwsh
      run: go build ./...

    # -------- tests + coverage --------
    # Linux/macOS: usa Makefile (make está disponível)
    - name: test with coverage (make)
      if: inputs.os-tag != 'windows'
      shell: bash
      run: make test.ci

    # Windows: não assume make; roda go test direto e escreve no mesmo path ./.tmp/coverage.out
    - name: test with coverage (windows)
      if: inputs.os-tag == 'windows'
      shell: pwsh
      run: |
        $tmp = "$(Get-Location)/.tmp"
        New-Item -ItemType Directory -Force -Path $tmp | Out-Null
        go test ./... -coverpkg=./joi -coverprofile="$tmp/coverage.out" -covermode=atomic

    # -------- artifacts --------
    - name: Upload coverage artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-${{ inputs.os-tag }}-go${{ inputs.go-tag }}
        path: ./.tmp/coverage.out

    # -------- codecov --------
    - name: Upload to Codecov
      if: ${{ inputs.codecov == 'true' }}
      uses: codecov/codecov-action@v4
      with:
        files: ./.tmp/coverage.out
        flags: ${{ inputs.os-tag }}-go${{ inputs.go-tag }}
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
