name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # ---------- Linux (usa container oficial do Go "1" = latest 1.x) ----------
  test-linux:
    name: test (linux, latest go1.x)
    runs-on: ubuntu-latest
    container:
      image: golang:1
    steps:
      - uses: actions/checkout@v4

      - name: Go env
        run: |
          go version
          go env

      - uses: ./.github/actions/go-ci
        with:
          os-tag: ubuntu
          go-tag: go1.x
          codecov: "true"
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  # ---------- macOS (setup-go: latest estável) ----------
  test-macos:
    name: test (macos, latest stable)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go (stable)
        uses: actions/setup-go@v5
        with:
          go-version: stable        # sempre a última versão estável
          check-latest: true        # força pegar o último patch

      - uses: ./.github/actions/go-ci
        with:
          os-tag: macos
          go-tag: stable
          codecov: "true"
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  # ---------- Windows (setup-go: latest estável) ----------
  test-windows:
    name: test (windows, latest stable)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go (stable)
        uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true

      - uses: ./.github/actions/go-ci
        with:
          os-tag: windows
          go-tag: stable
          codecov: "true"
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
