name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # ---------- Linux (container golang:<version>) ----------
  test-linux:
    name: test (${{ matrix.go }}, ubuntu-latest)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.x.x' ]
    container:
      image: golang:${{ matrix.go }}
    steps:
      - uses: actions/checkout@v4
      - name: Go env
        run: |
          go version
          go env
      - uses: ./.github/actions/go-ci
        with:
          os-tag: ubuntu
          go-tag: ${{ matrix.go }}
          codecov: "true"
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  # ---------- macOS ----------
  test-macos:
    name: test (${{ matrix.go }}, macos-latest)
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.x.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - uses: ./.github/actions/go-ci
        with:
          os-tag: macos
          go-tag: ${{ matrix.go }}
          codecov: "true"
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  # ---------- Windows ----------
  test-windows:
    name: test (${{ matrix.go }}, windows-latest)
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.x.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - uses: ./.github/actions/go-ci
        with:
          os-tag: windows
          go-tag: ${{ matrix.go }}
          codecov: "true"
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
